name: 'Auto Assign'
on:
  workflow_call:
    inputs:
      reviewers:
        required: false
        type: string
        description: "Comma-separated list of reviewers"
      numberOfReviewers:
        required: false
        type: number
        description: "Number of reviewers to add"
      skipKeywords:
        required: false
        type: string
        description: "Keywords to skip"

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          addReviewers: true
          addAssignees: author
          reviewers: ${{ inputs.reviewers }}
          numberOfReviewers: ${{ inputs.numberOfReviewers }}
          skipKeywords: ${{ inputs.skipKeywords }}

