name: 'Auto Assign'
on:
  workflow_call:
    inputs:
      reviewers:
        required: false
        type: string
        description: "Comma-separated list of reviewers"
      numberOfReviewers:
        required: false
        type: number
        description: "Number of reviewers to add"
      skipKeywords:
        required: false
        type: string
        description: "Keywords to skip"

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          # configuration-path: '.github/auto_assign.yml'
          reviewers: "marten-nilsson, RohitGoyani"
          numberOfReviewers: 0
          skipKeywords: "wip"
          addReviewers: true

