name: 'Auto Assign'
on:
  workflow_call:
    inputs:
      configuration_path:
        required: true
        type: string
        description: ""

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: 'sakshi-devotess/github-action/.github/auto_assign.yml@main'

