name: Deploy to Glesys STAGE

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
        description: "The hostname for the server"
      user:
        required: true
        type: string
        description: "The user for SSH"
      target:
        required: true
        type: string
        description: "The target environment"
      destination:
        required: true
        type: string
        description: "Destination path on the server"
      fingerprint:
        required: false
        type: string
        description: "SSH fingerprint"
    secrets:
      password:
        required: true
      dotenv_key:
        required: true

jobs:
  deploy:
    uses: 'sakshi-devotess/github-action/.github/workflows/deploy.yml@development'
    with:
      hostname: ${{ inputs.hostname }}
      user: ${{ inputs.user }}
      target: ${{ inputs.target }}
      destination: ${{ inputs.destination }}
      fingerprint: ${{ inputs.fingerprint }}
    secrets:
      password: ${{ secrets.STG_PASSWORD }}
      dotenv_key: ${{ secrets.STG_DOTENV_KEY }}
  
