name: Deploy to Glesys STAGE

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
        description: "The hostname for the server"
      user:
        required: true
        type: string
        description: "The user for SSH"
      target:
        required: true
        type: string
        description: "The target environment"
      destination:
        required: true
        type: string
        description: "Destination path on the server"
      fingerprint:
        required: false
        type: string
        description: "SSH fingerprint"
      password:
        required: false
        type: string
        description: "Password for the server"
      dotenv_key:
        required: false
        type: string
        description: "Key for the .env file"
      pm2_name:
        required: true
        type: string
        description: "Name for the pm2 process"
      service_type:
        required: true
        type: string
        default: "frontend"
        description: "Type of service to deploy (front or back)"
      mode:
        required: false
        type: string
        description: "Mode for the backend service"
    secrets:
      password:
        required: true
      dotenv_key:
        required: true
      dotenv_me:
        required: false 

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print service type
        run: |
          echo "Service type: ${{ inputs.service_type }}"
          if [ "${{ inputs.service_type }}" == "frontend" ]; then
            echo "This is a frontend deployment."
          elif [ "${{ inputs.service_type }}" == "backend" ]; then
            echo "This is a backend deployment."
          else
            echo "Service type does not match frontend or backend."
          fi
  deploy-front:
    if: ${{ inputs.service_type == 'frontend' }}
    uses: 'sakshi-devotess/github-action/.github/workflows/deploy-frontend.yml@main'
    with:
      hostname: ${{ inputs.hostname }}
      user: ${{ inputs.user }}
      target: ${{ inputs.target }}
      destination: ${{ inputs.destination }}
      fingerprint: ${{ inputs.fingerprint }}
      pm2_name: ${{ inputs.pm2_name }}
    secrets:
      password: ${{ secrets.password }}
      dotenv_key: ${{ secrets.dotenv_key }}

  deploy-back:
    if: ${{ inputs.service_type == 'backend' }}
    uses: 'sakshi-devotess/github-action/.github/workflows/deploy-backend.yml@main'
    with:
      hostname: ${{ inputs.hostname }}
      user: ${{ inputs.user }}
      target: ${{ inputs.target }}
      destination: ${{ inputs.destination }}
      fingerprint: ${{ inputs.fingerprint }}
      pm2_name: ${{ inputs.pm2_name }}
      mode: ${{ inputs.mode }}
    secrets:
      password: ${{ secrets.password }}
      dotenv_key: ${{ secrets.dotenv_key }}
      dotenv_me: ${{ secrets.dotenv_me }}
  
