name: 'Prettier dry run'
on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: --check **/*.tsx
