name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string
    secrets:
      token:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  prettier:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check branch protection and Prettier status check
        id: check-branch-protection
        uses: actions/github-script@v6
        with:
          script: |
            const branch = 'main';
            try {
              const { data } = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
              });
              console.log(data);
            } catch (error) {
              console.log(error.message);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
