name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string
      repository:
        description: 'The repository to check for PRs'
        required: true
        type: string
    secrets:
      token:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  prettier:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check branch protection using GitHub Script
        id: check-branch-protection
        uses: actions/github-script@v6
        with:
          script: |
            const repository = '${{ inputs.repository }}';
            const [owner, repo] = repository.split('/');
            
            try {
              const response = await github.request('GET /repos/{owner}/{repo}/branches/{branch}/protection', {
                owner,
                repo,
                branch: 'main',
              });
              console.log('Branch protection details:', response.data);
            } catch (error) {
              console.error('Failed to fetch branch protection:', error.message);
              core.setFailed(error.message);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
