name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check branch protection and Prettier status check
        id: check-branch-protection
        uses: actions/github-script@v6
        with:
          script: |
            const branch = 'main'; // Change to your branch name if different
            const requiredJob = 'prettier'; // The job name to check
            try {
              const { data } = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
              });
              const requiredChecks = data.required_status_checks?.contexts || [];
              if (!requiredChecks.includes(requiredJob)) {
                core.setFailed(`The job "${requiredJob}" is not listed in "Require status checks to pass before merging" for branch "${branch}".`);
              }
            } catch (error) {
              if (error.status === 404) {
                core.setFailed(`Branch protection is not configured for branch "${branch}".`);
              } else {
                throw error;
              }
            }

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
