name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string
      repository:
        description: 'The repository to check for PRs'
        required: true
        type: string
    secrets:
      token:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  prettier:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check branch protection using GitHub Script
        id: check-branch-protection
        run: |
          gh api repos/${{ inputs.repository }}/branches/main/protection \
            --method GET \
            --header "Authorization: token ${{ secrets.token }}" \
            --jq '.'

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
