name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line

jobs:
  validate-branch-protection:
    uses: .github/workflows/check-branch-protection.yml
    with:
      branch_name: 'main'
      required_jobs: 'Prettier'

  prettier:
    needs: validate-branch-protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: --check **/*.tsx
